<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FAI-BLR04L1349" ignored="2" name="Default test(failed)" tests="2" failures="1" timestamp="08 Apr 2019 10:42:33 GMT" time="0.081" errors="0">
  <testcase name="test3" time="0.019" classname="Demo.TestNGRetryFailedDemo"/>
  <testcase name="test2" time="0.006" classname="Demo.TestNGRetryFailedDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Demo.TestNGRetryFailedDemo.test2(TestNGRetryFailedDemo.java:24)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.0" classname="Demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test1" time="0.0" classname="Demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
